name: build

# Trigger on pull requests
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v19
        id: vercel-deployment
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GH_TOKEN }}
          vercel-args: '--build-env API_URL=${{ secrets.API_URL }}'
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: ./

      - name: Build log
        if: ${{ always() }}
        run: |
          vercel -t ${{ secrets.VERCEL_TOKEN }} logs ${{ steps.vercel-deployment.outputs.preview-url }}
