name: build

# Trigger on pull requests
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-

      - name: Install node modules
        run: |
          echo Installing node modules...
          yarn install

      - name: Lint
        run: |
          echo Running lints...
          yarn lint
          yarn lint-style

      - name: Build
        env:
          API_URL: ${{ secrets.API_URL }}
        run: |
          echo Building...
          yarn run build --prefix-paths
